docs/source/metadatenabgabe.rst

Please check whether I have forgotten anything and whether this makes sense.

delete hard deprecated excel import (study, survey, instrument) (#1919)

---

src/main/webapp/scripts/datasetmanagement/views/data-set-edit-or-create.controller.js
src/main/webapp/scripts/searchmanagement/directives/data-set-search-result.directive.js
src/main/webapp/scripts/searchmanagement/directives/survey-search-result.directive.js
src/main/webapp/scripts/studymanagement/views/study-detail.controller.js
src/main/webapp/scripts/surveymanagement/views/survey-edit-or-create.controller.js

#1922 Refresh studies index on dataset or survey creation/deletion

---

src/main/webapp/scripts/common/i18n/configuration/translations-de.js
src/main/webapp/scripts/common/i18n/configuration/translations-en.js
src/main/webapp/scripts/dataacquisitionprojectmanagement/directives/metadata-type-state-card.directive.js
src/main/webapp/scripts/searchmanagement/views/search.controller.js

Resolves #1963 for IE. Needs additional confirmation that Edge doesn't exhibit this problem.

#1963 Provide a message that edge/ie cannot upload directories

---

src/main/webapp/scripts/dataacquisitionprojectmanagement/directives/metadata-type-state-card.directive.js
src/main/webapp/scripts/dataacquisitionprojectmanagement/directives/metadata-type-state-card.html.tmpl
src/main/webapp/scripts/dataacquisitionprojectmanagement/directives/user-list.directive.js
src/main/webapp/scripts/dataacquisitionprojectmanagement/directives/user-list.html.tmpl
src/main/webapp/scripts/dataacquisitionprojectmanagement/services/projectUpdateAccessService.js
src/main/webapp/scripts/dataacquisitionprojectmanagement/views/project-cockpit.controller.js
src/main/webapp/scripts/dataacquisitionprojectmanagement/views/project-cockpit.html.tmpl

Fixes user assignment bug introduced with the directive split.
Should resolve #1984.

Systemcluster/issue1984 Adjust user assignment logic & correct projectUpdateService assignment check

---

docs/source/javadoc/eu/dzhw/fdz/metadatamanagement/ordermanagement/domain/OrderAlreadyCompletedException.rst
docs/source/javadoc/eu/dzhw/fdz/metadatamanagement/ordermanagement/domain/package-index.rst
src/main/java/eu/dzhw/fdz/metadatamanagement/common/rest/errors/ExceptionTranslator.java
src/main/java/eu/dzhw/fdz/metadatamanagement/ordermanagement/domain/Order.java
src/main/java/eu/dzhw/fdz/metadatamanagement/ordermanagement/domain/OrderAlreadyCompletedException.java
src/main/java/eu/dzhw/fdz/metadatamanagement/ordermanagement/rest/OrderResource.java
src/main/java/eu/dzhw/fdz/metadatamanagement/ordermanagement/service/OrderService.java
src/main/webapp/scripts/ordermanagement/views/shopping-cart.controller.js
src/test/java/eu/dzhw/fdz/metadatamanagement/ordermanagement/rest/OrderResourceTest.java

- Add NotNull to order state
- Prevent order losing it's createdBy, createdDate and state field on update
- Prevent updates on orders with state 'ORDERED'

Es flavia/issue1921

---

docs/source/questions.rst
docs/source/uebersicht_rscripte.rst

Please check. This would close #2006

make question images not mandatory (closes #2006)

---

src/main/webapp/scripts/studymanagement/configuration/translations-de.js
src/main/webapp/scripts/studymanagement/configuration/translations-en.js
src/main/webapp/scripts/studymanagement/views/study-detail.html.tmpl

#1908 Replace beta release text and hide waves field if wave count is 0

---

Gruntfile.js
src/main/java/eu/dzhw/fdz/metadatamanagement/common/service/AttachmentMetadataHelper.java
src/main/java/eu/dzhw/fdz/metadatamanagement/datasetmanagement/service/DataSetAttachmentService.java
src/main/java/eu/dzhw/fdz/metadatamanagement/instrumentmanagement/service/InstrumentAttachmentService.java
src/main/java/eu/dzhw/fdz/metadatamanagement/studymanagement/service/StudyAttachmentService.java
src/main/java/eu/dzhw/fdz/metadatamanagement/surveymanagement/service/SurveyAttachmentService.java
src/main/webapp/scripts/studymanagement/views/study-detail.controller.js

* Prevent losing content type on attachment metadata updates (#2115)
* Prevent access on undefined field causing the study details view to not initialize properly (#2114)

Hotfix for issue #2115 and #2114

---

Gruntfile.js
src/main/webapp/scripts/datasetmanagement/services/dataSetSearch.service.js
src/main/webapp/scripts/datasetmanagement/views/dataSet-detail.controller.js
src/main/webapp/scripts/questionmanagement/services/questionSearch.service.js
src/main/webapp/scripts/relatedpublicationmanagement/services/relatedPublicationSearch.service.js
src/main/webapp/scripts/surveymanagement/services/surveySearch.service.js
src/main/webapp/scripts/surveymanagement/views/survey-detail.controller.js
src/main/webapp/scripts/variablemanagement/services/variableSearch.service.js
src/main/webapp/scripts/variablemanagement/views/variable-detail.controller.js

* Count query now considers the possibility that shadow copies might exist
* Removed some dead code from various search services

Wrong panel variables count (Issue #2117)

---

src/main/webapp/scripts/studymanagement/views/study-detail.controller.js

Access on undefined field prevented initialization of the tag field.

(Tags) #1800 Fix access on undefined version field

---

src/main/java/eu/dzhw/fdz/metadatamanagement/surveymanagement/domain/SurveySampleTypeProvider.java

Adjust spelling so that it matches the official VFDB spelling which is
"Probability Sampie".

#2159 Adjust spelling for Probability Sample

---

src/test/robotframework/public_user/studymanagement/keyword_search_and_view.robot
src/test/robotframework/public_user/studymanagement/keyword_serach_and_view.robot

Merge Saikotitis/issue2165 into development

---

src/test/robotframework/data_provider/datasetmanagement/upload_variable_report.robot

- variable report folder upload does not work anymore in this test case
- single file upload work only in firefox

Merge Saikotitis/issue2148 into development

---

src/test/robotframework/data_provider/datasetmanagement/upload_variable_report.robot
src/test/robotframework/publisher/Projectoverview/Check Post Validation Errors for Projects.robot

- robot test for checking post validation of projects

Merger Saikotitis/issue2225 in to development

---

src/test/robotframework/data_provider/datasetmanagement/upload_variable_report.robot
src/test/robotframework/publisher/Projectoverview/Check Different Icons of Projects from Projectoverview.robot
src/test/robotframework/publisher/Projectoverview/Check Post Validation Errors for Projects.robot

- test Implementation for checking icons of metada from projectoverview

Merge Saikotitis/issue2226 in to development

---

src/main/webapp/scripts/ordermanagement/configuration/translations-de.js
src/main/webapp/scripts/ordermanagement/configuration/translations-en.js
src/main/webapp/scripts/ordermanagement/views/shopping-cart.html.tmpl

Optional study series is now referenced through the shadow copy id instead
of master id.

Issue 2101: Add study series link to products in shopping cart

---

package-lock.json
package.json
src/main/webapp/index.html
src/main/webapp/scripts/app.js
src/main/webapp/scripts/common/pagination/custom-uib-pagination.html.tmpl
src/main/webapp/scripts/disclosure/configuration/disclosure.js
src/main/webapp/scripts/ordermanagement/configuration/shoppingCart.js

Remove angular-scroll

---

buildconfig/google_checks.xml
eclipseconfig/eclipse-java-google-style.xml
src/main/java/eu/dzhw/fdz/metadatamanagement/common/domain/util/Patterns.java
src/main/java/eu/dzhw/fdz/metadatamanagement/datapackagemanagement/domain/DataPackageAttachmentMetadata.java
src/main/webapp/scripts/common/dialogs/attachment/attachment-edit-or-create.html.tmpl
src/main/webapp/scripts/common/dialogs/attachment/configuration/translations-de.js
src/main/webapp/scripts/common/dialogs/attachment/configuration/translations-en.js
src/main/webapp/scripts/datapackagemanagement/components/attachments.html.tmpl
src/main/webapp/scripts/datapackagemanagement/views/data-package-edit-or-create.html.tmpl

…validation, added ui integration.

closes #2989 

---

pom.xml

updated spring boot to 2.5.13

---

src/main/webapp/scripts/datapackagemanagement/templates/attachments.html.tmpl

Solving issue #3104 dataset and instument sections are unfolded by default

#3104 set dataset and instrument sections uncollapsed by default

---

buildconfig/google_checks.xml
eclipseconfig/eclipse-java-google-style.xml
src/main/java/eu/dzhw/fdz/metadatamanagement/common/domain/util/Patterns.java
src/main/java/eu/dzhw/fdz/metadatamanagement/datapackagemanagement/domain/DataPackageAttachmentMetadata.java
src/main/scss/main.scss
src/main/webapp/index.html
src/main/webapp/scripts/common/dialogs/attachment/attachment-edit-or-create.html.tmpl
src/main/webapp/scripts/common/dialogs/attachment/configuration/translations-de.js
src/main/webapp/scripts/common/dialogs/attachment/configuration/translations-en.js
src/main/webapp/scripts/datapackagemanagement/components/attachments.html.tmpl
src/main/webapp/scripts/datapackagemanagement/views/data-package-edit-or-create.html.tmpl

This includes changes to the style to load fonts from a local source and adds the DOI attribute to data package attachments (#2989).

Google Fonts Hotfix + DOI Attribute for data package attachments (#2989)

---

src/main/webapp/scripts/datapackagemanagement/configuration/translations-de.js
src/main/webapp/scripts/datapackagemanagement/configuration/translations-en.js
src/main/webapp/scripts/datapackagemanagement/views/data-package-edit-or-create.html.tmpl

#3151: added consent info text (annotaion and description field)

#3151: added consent info text

---

src/main/webapp/scripts/ordermanagement/configuration/translations-de.js
src/main/webapp/scripts/ordermanagement/configuration/translations-en.js

added hint text for analysis package shopping cart

---

src/main/webapp/scripts/common/footer/footer.html.tmpl
src/main/webapp/scripts/disclosure/views/disclosure.html.tmpl

updated disclosure page and front page

#3152 updated infos

---

src/main/webapp/scripts/analysispackagemanagement/views/analysis-package-edit-or-create.html.tmpl
src/main/webapp/scripts/common/text/text-bilingual.html.tmpl
src/main/webapp/scripts/common/textsection/edit-text-section.bilingual.html.tmpl

Supplement: In addition to the datapackage-form, I added the hints about consent on cc0 license also to the analysispackage-form

#3151: added consent hints to analysispackage-form

---

.jscsrc
src/main/webapp/scripts/common/i18n/configuration/translations-de.js
src/main/webapp/scripts/common/i18n/configuration/translations-en.js
src/main/webapp/scripts/ordermanagement/configuration/translations-de.js
src/main/webapp/scripts/ordermanagement/configuration/translations-en.js
src/main/webapp/scripts/relatedpublicationmanagement/services/relatedPublicationSearch.service.js
src/main/webapp/scripts/searchmanagement/components/menu-toggle.html.tmpl
src/main/webapp/scripts/searchmanagement/components/related-publications-info.html.tmpl
src/main/webapp/scripts/searchmanagement/components/searchfilter.controller.js
src/main/webapp/scripts/searchmanagement/components/searchfilter.html.tmpl
src/main/webapp/scripts/searchmanagement/configuration/translations-de.js
src/main/webapp/scripts/searchmanagement/configuration/translations-en.js
src/main/webapp/scripts/searchmanagement/directives/search-filter-panel.controller.js
src/main/webapp/scripts/searchmanagement/services/search.dao.js
src/main/webapp/scripts/searchmanagement/services/searchHelper.service.js
src/main/webapp/scripts/searchmanagement/views/search.controller.js
src/main/webapp/scripts/searchmanagement/views/search.html.tmpl
src/main/webapp/scripts/start/views/start.controller.js

Solves #3095 enabling search for related publications

#3095 filter for related publications

---

src/main/webapp/scripts/searchmanagement/views/search.controller.js

Fixing loading of total count of documents in search tabs on search page for authenticated users

Problem with loading total count of documents in tabs

---

src/main/webapp/scripts/ordermanagement/components/analysis-package-configurator.html.tmpl
src/main/webapp/scripts/ordermanagement/components/data-package-configurator.html.tmpl
src/main/webapp/scripts/ordermanagement/configuration/translations-de.js
src/main/webapp/scripts/ordermanagement/configuration/translations-en.js

Added hint on order menu, commented in code for easy removal

#3194 added maintenance hint for ordering process

---

package-lock.json
package.json
pom.xml

added maintenance hint for order process

added maintenance hint for order process

---

src/main/webapp/scripts/ordermanagement/components/analysis-package-configurator.controller.js
src/main/webapp/scripts/ordermanagement/components/analysis-package-configurator.html.tmpl
src/main/webapp/scripts/ordermanagement/components/data-package-configurator.controller.js
src/main/webapp/scripts/ordermanagement/components/data-package-configurator.html.tmpl

displaying maintenance hints is now configurable within the component

#3194 improved implementation with configuration variable

---

src/main/java/eu/dzhw/fdz/metadatamanagement/datapackagemanagement/domain/DataPackage.java
src/main/java/eu/dzhw/fdz/metadatamanagement/datapackagemanagement/service/DataPackageOverviewService.java
src/main/java/eu/dzhw/fdz/metadatamanagement/datasetmanagement/domain/DataSet.java
src/main/java/eu/dzhw/fdz/metadatamanagement/datasetmanagement/service/DataSetReportService.java

Reformats title and description strings to avoid line break errors with latex generation

#3188 fix report generation

---

terraform/main.tf

Updated terraform files to latest syntax requirements to enable execution of terraform.

#3217 updated dara endpoint url and terraform files

---

mdm-frontend/package.json
mdm-frontend/src/app/app.module.ts
mdm-frontend/src/app/legacy/searchmanagement/directives/analysis-package-search-result.html.tmpl
mdm-frontend/src/app/legacy/searchmanagement/directives/data-package-search-result.html.tmpl
pom.xml

Visibility of action link to deep search within data package and analysis package is non-privileged now (closes #3248).

Bugfix Release 2023.1.2

---

README.md
mdm-frontend/src/app/legacy/datapackagemanagement/configuration/translations-de.js
mdm-frontend/src/app/legacy/datapackagemanagement/configuration/translations-en.js
mdm-frontend/src/app/legacy/datapackagemanagement/templates/common-details.html.tmpl
mdm-frontend/src/app/legacy/datapackagemanagement/views/data-package-detail.controller.js
mdm-frontend/src/app/legacy/datapackagemanagement/views/data-package-edit-or-create.controller.js
mdm-frontend/src/app/legacy/datapackagemanagement/views/data-package-edit-or-create.html.tmpl
mdm-frontend/src/app/legacy/ordermanagement/components/data-package-configurator.controller.js
src/main/java/eu/dzhw/fdz/metadatamanagement/datapackagemanagement/domain/DataPackage.java
src/main/java/eu/dzhw/fdz/metadatamanagement/ordermanagement/domain/OrderedDataPackage.java
src/main/java/eu/dzhw/fdz/metadatamanagement/ordermanagement/rest/OrderResource.java

DLP-Ticket: https://github.com/dzhw/dlp-dienstleistungsportal/issues/419
Issue: https://github.com/dzhw/metadatamanagement/issues/3233

#3233 Add remarks attribute with additional information for the user service

---

mdm-frontend/src/app/legacy/common/dialogs/attachment/attachmentDialog.controller.js
mdm-frontend/src/app/legacy/common/dialogs/attachment/configuration/translations-de.js

also: outsourcing of string into translations file.

#3239: adjusted value for description field

---

src/main/resources/config/application-prod.yml

Fix mongock changelog package names

Fix mongock changelog package names

---

mdm-frontend/src/app/legacy/common/dialogs/attachment/configuration/translations-de.js
mdm-frontend/src/app/legacy/common/i18n/configuration/translations-de.js
mdm-frontend/src/app/legacy/dataacquisitionprojectmanagement/configuration/translations-de.js
mdm-frontend/src/app/legacy/dataacquisitionprojectmanagement/configuration/translations-en.js
mdm-frontend/src/app/legacy/dataacquisitionprojectmanagement/views/release-project-dialog.controller.js

https://github.com/dzhw/metadatamanagement/issues/3263

#3263 Fallback strategy for when DA|RA is not reachable

---

mdm-frontend/src/app/legacy/relatedpublicationmanagement/services/relatedPublicationBuilder.service.js

because response of poi.org is not uniform

#3341: removed doi.org request

---

mdm-frontend/src/app/legacy/datasetmanagement/configuration/translations-de.js

Addendum to #3256 
replaces PR #3355 
Original description by @ewolf47 :
see this https://github.com/dzhw/metadatamanagement/issues/3302#issuecomment-2191044752

#3256: edited default description according to the specifications of Anne Weber (26.06.2024)

---

mdm-frontend/angular.json
mdm-frontend/src/app/legacy/common/dialogs/jsoncontentdialog/jsonContentDialog.controller.js
mdm-frontend/src/app/legacy/common/dialogs/jsoncontentdialog/jsonContentDialog.directive.js
mdm-frontend/src/app/legacy/ordermanagement/components/data-package-configurator.html.tmpl

- fixes the bug of citiations in data packages always being disabled
- also fixes the broken show as JSON dialog mentioned in issue #3347

#3323 Citation bug

---

mdm-frontend/src/app/dataacquisitionprojectmanagement/dataacquisitionproject.search.service.ts
mdm-frontend/src/app/legacy/dataacquisitionprojectmanagement/configuration/translations-de.js
mdm-frontend/src/app/legacy/dataacquisitionprojectmanagement/configuration/translations-en.js
mdm-frontend/src/app/legacy/dataacquisitionprojectmanagement/views/project-overview.controller.js
mdm-frontend/src/app/legacy/dataacquisitionprojectmanagement/views/project-overview.html.tmpl
src/main/java/eu/dzhw/fdz/metadatamanagement/datapackagemanagement/service/DataPackageManagementService.java
src/main/java/eu/dzhw/fdz/metadatamanagement/projectmanagement/domain/DataAcquisitionProject.java
src/main/java/eu/dzhw/fdz/metadatamanagement/searchmanagement/service/ElasticsearchUpdateQueueService.java
src/main/resources/elasticsearch/data_acquisition_projects/mapping.json
src/test/java/eu/dzhw/fdz/metadatamanagement/common/unittesthelper/util/UnitTestCreateDomainObjectUtils.java

 Add filters for new attributes resulting from #2770 & #3257 

---

src/main/java/eu/dzhw/fdz/metadatamanagement/datapackagemanagement/service/DataPackageDdiService.java

#3304 Fixed variable name attribute in DDI Codebook mapping

---

src/main/java/eu/dzhw/fdz/metadatamanagement/projectmanagement/service/DataCiteService.java
terraform/elastic_container_service.tf
terraform/templates/web_container.json.tpl
terraform/templates/worker_container.json.tpl

terraform config, improved error handling

#3240 doi registration mapping implementation 

---

src/main/java/eu/dzhw/fdz/metadatamanagement/projectmanagement/service/DataCiteService.java

- resource type of analysis packages set to "Collection"
- removed German affiliation from creator and contributor objects

#3240: addition to datacite registration
